name: Publish and Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main  # mainブランチにプッシュされた時に実行

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        docker-compose up -d
        docker-compose ps

    - name: Wait for MySQL to be ready
      run: |
        while ! docker-compose exec mysql mysqladmin ping --silent; do sleep 1; done

    - name: Create tables
      run: docker-compose exec -T mysql mysql -uuser -ppassword todo_database < sql/create_tables.sql

    - name: Set up tbls
      uses: k1low/setup-tbls@v1

    - name: Generate docs
      run: tbls doc

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./docs  # ドキュメントが生成されるパス

    - name: Deploy to GitHub Pages
      if: success()
      uses: actions/deploy-pages@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
