services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: todo_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
