site_name: DB Schema  # サイトの名前

theme:
  name: material  # テーマの名前
  language: ja  # 使用する言語

plugins:
  - search  # 検索機能の追加
  - include-markdown  # Markdownファイルをインクルードするプラグイン
  - glightbox  # 画像のライトボックス表示用プラグイン

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true  # 行番号のアンカーを表示
      line_spans: __span  # 行のスパンのクラス名を設定
      pygments_lang_class: true  # 言語クラスをPygmentsのスタイルで設定
  - pymdownx.inlinehilite  # インラインハイライトの有効化
  - pymdownx.snippets  # スニペット機能の有効化
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed  # タブ付きコンテンツの有効化
  - pymdownx.superfences  # スーパーフェンス機能の有効化
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji  # Twemojiを使用した絵文字インデックス
      emoji_generator: !!python/name:materialx.emoji.to_svg  # SVG形式の絵文字生成
  - attr_list  # ボタン表示のための属性リスト

docs_dir: tbls_gen_docs
site_dir: mkdocs_gen_docs
