site_name: DB Schema

theme:
  name: material
  language: ja

plugins:
  - search
  - include-markdown
  - glightbox

# Ref: tblsのViewPoint機能を用いたGithub Actions上でのDBドキュメントの自動生成 - https://engineers.safie.link/entry/2023/12/02/build-db-doc-by-tbls#skeema-%E3%81%AB%E3%82%88%E3%82%8BDB%E3%82%B9%E3%82%AD%E3%83%BC%E3%83%9E%E3%81%AE%E9%81%A9%E7%94%A8
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.superfences
  - admonition
  - attr_list

docs_dir: tbls_gen_docs
site_dir: mkdocs_gen_docs
