site_name: DB Schema

theme:
  name: material
  language: ja

plugins:
  - search
  - include-markdown
  - glightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

docs_dir: tbls
site_dir: mkdocs
