name: mkdocs deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install mkdocs and plugins
      run: |
        pip install -r requirements.txt

    - name: Build MkDocs site
      run: |
        mkdocs gh-deploy --force
