name: Publish and Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: todo_database
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
        - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping --host=127.0.0.1 --user=user --password=password --silent; do sleep 1; done

    - name: Create tables
      run: |
        mysql --host=127.0.0.1 --user=user --password=password todo_database < sql/create_tables.sql

    - name: Set up tbls
      uses: k1low/setup-tbls@v1

    - name: Generate docs
      run: |
        tbls doc

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs

  deploy:
      needs: build

      permissions:
        pages: write
        id-token: write

      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
